projects:
  dev-sup-host-appsync:
    schemaPath: client/amplify/graphql/schema.json
    includes:
      - client/amplify/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: client/amplify/API.ts
        docsFilePath: client/amplify/graphql
        region: ap-northeast-1
        apiId: xwfpm2gsn5fg7apvf6eowpwhbi
        maxDepth: 10
extensions:
  amplify:
    version: 3
